### PR TITLE
WIP: Multiple interfaces

### PR DESCRIPTION
**Pull request by mido0258**
This is a working part of interfaces, it is questionable if  is using attributes good for this feature  and also I understand there might be some stuff I forgot to update. Please let me know if you want me to update something (at least README should be updated).

### CODE REVIEW

**Comment by AzureMarker** [comment]
Hi, can you explain what the goal of this change is?

**Comment by mido0258** [comment]
can we hop on some call might be faster, thats my first pull request

**Comment by mido0258** [comment]
Either way the point is descibed here:  https://github.com/AzureMarker/shaku/issues/36 basically be able to inject multiple implementations of an trait

**Comment by AzureMarker** [comment]
There are a few issues with the PR right now:
1. It's not clear why this feature is needed. The issue you referenced was closed and does not give a clear use case for this feature. It sounds like you don't know why this feature is needed either? "I am willing to fix issues with integrations [..] as long there will be someone who actually want this feature"
2. It introduces a breaking change unnecessarily.
3. The documentation and guide have not been updated to explain the feature or why it's useful/needed.
4. CI is failing.

**Comment by mido0258** [comment]
Well I am going to use this feature in my projects, feel free to close if you feel that it's  not needed, I just wanted to create PR , as i saw (even closed) question. I am aware of other issues with this PR but if tis is not needed I am not going to spend time on it.

**Comment by AzureMarker** [comment]
That's fair. I'm just making sure that the library is built to solve compelling use cases and minimizes the burden on consumers to keep up to date. If the issues I mentioned get resolved then I'll be happy to discuss merging the PR. Until then, I'll close it.

**Pull request closed without merging**
