### PR TITLE
Fix for RUSTSEC-2021-0065 (Issue 48)

### PR DESCRIPTION
**Pull request by wolpert**
Upgraded to anymap2. Anymap 0.12.1 and earlier have a vulnerability and the project is unmaintained. Moving to the maintained anymap2 project. Fix for https://github.com/AzureMarker/shaku/issues/48 re: https://rustsec.org/advisories/RUSTSEC-2021-0065.html

### CODE REVIEW

**Comment by wolpert** [comment]
The failure in shaku-msrv build step was with Cargo.lock.msrv not being updated. Not sure what the normal process is here for you.

**Comment by AzureMarker** [comment]
Thanks @wolpert, I'll take a look at this soon.

**Comment by AzureMarker** [comment]
Thanks for the PR!

**Comment by AzureMarker** [comment]
Released in v0.6.2

**Pull request merged**
